### ISSUE TITLE
技大祭の年度情報

### ISSUE THREAD

**Issue by TKNGUE** [NUTFes/group-manager#116]
1. シードの情報の改善が必要
2. purchase_listの年度情報が間違っている

**Comment by yyamnk** [comment]
`app/views/purchase_lists/index_cooking.html.erb`と
`app/views/purchase_lists/index_noncooking.html.erb`で

```
<% fes_dates = FesDate.all %>
```

を書き換えましょう．

**Comment by ShuzoN** [comment]
1番は, 抽象的すぎるので無視. 
2番は, 消化済み.
