### ISSUE TITLE
購入リストで1日目と2日目で「同じ仕入先」を選択できない問題

### ISSUE THREAD

**Issue by ShuzoN** [NUTFes/group-manager#152]
購入リストで1日目で入力した「仕入先」が2日目の入力画面で表示されない. 
![2016-07-09 14 29 39](https://cloud.githubusercontent.com/assets/5877377/16706292/bafbff44-45e1-11e6-89bb-3e221160d41c.jpg)
1日目で「山久流通」を選択する. 

![2016-07-09 14 29 55](https://cloud.githubusercontent.com/assets/5877377/16706294/bc376bdc-45e1-11e6-9cc8-d798912d50af.jpg)
2日目で仕入先に「山久流通」が表示されない

**Comment by yyamnk** [comment]
@ShuzoN 
山久流通は日曜が定休日で登録されているので，9/18 (日) の購入先に表示されないです．
なのでバグではないですね．

**Comment by ShuzoN** [comment]
@yyamnk ありがとうございます!!
