### ISSUE TITLE
本番環境のテストデータを削除する

### ISSUE THREAD

**Issue by ShuzoN** [NUTFes/group-manager#153]
締切 8/10

本番環境に大量のテストデータが存在する. 
書類を自動生成する際, テストデータも出力に含まれてしまうため厄介. 

そこで, 本番環境からテストデータを全削除する.
テストは全てステージング環境で行うことにする. 
## 依存issue #59

追記

とりあえず, この方法でテストデータを退避.

> > 年度テーブルのシードに 適当なidの年度(e.g. 1000001)を追加して,
> > テストデータをその年度に移す

ゆくゆくはissue#59の機能により, テストデータを本番環境から削除する方針に決定

**Comment by takegue** [comment]
一番簡単そうな解決方法は, テストデータの年度情報を 書き換えてしまうのが良さそう

**Comment by ShuzoN** [comment]
@TKNGUE 頭良すぎる

**Comment by ShuzoN** [comment]
ユーザが「manager, developer」権限 && 年度が「2016」 の団体を「2015」に書き換える, ってスクリプトで対処します. せるふあさいん

**Comment by yyamnk** [comment]
削除するんじゃダメなの?
2015に書き変えたら非管理者側のページには表示されないんじゃなかったっけ?
もはや不要なのでは?

**Comment by ShuzoN** [comment]
@yyamnk 本来はそうあるべきで, 確かにそうなんですよね. 
issue本文にも書きましたが, グループの削除は issue#59 に依存します. 
だから, 応急処置としては@TKNGUEのやり方は1つの選択肢としてはありですね.

**Comment by yyamnk** [comment]
@ShuzoN なるほど．そのissue忘れてました．すいません．
変更するなら過去の運用年度前にできるかな? (年度`0`とか．)
昨年度のデータと混ぜたくないので．

ただ年度は年度テーブル?に紐付いていたかも...

**Comment by ShuzoN** [comment]
@yyamnk 
仰るとおりで, 年度は年度テーブルに紐付いてますね. 
やはり, 過去の運用と混ぜたくない...かつその手間を考えると
根本解決が良さそうですね.

**Comment by takegue** [comment]
年度テーブルのシードに 適当なidの年度(e.g. 1000001)を追加して, 
テストデータをその年度に移すってのが, 混ざらないしコスト低いと思ったのだけど、どうだろう？
込み入った作業がいるのかな...？

**Comment by ShuzoN** [comment]
@TKNGUE 確かに. issue#59は遅かれ早かれ必要なので, とりあえず 

> > 年度テーブルのシードに 適当なidの年度(e.g. 1000001)を追加して,
> > テストデータをその年度に移す

で対処して, そのデータをゆくゆくは消す, って方針にしよう.

**Comment by ShuzoN** [comment]
### テストデータの判断が難しい件

issue #154 では, 管理者, 開発者権限で記入したデータの年度を書き換えるスクリプトを実装した. 

しかし, 国際祭りに関しては, 管理者が全ての団体のデータを入力している. 
そのため, 上記の方法では必要なデータも書き換えてしまう. 
このようなデータに対応できるようにバッチスクリプトを書く必要が出てきた.

**Comment by ShuzoN** [comment]
また, #155 でmergeしたスクリプト本番環境で実行するとエラーを吐くため検証が必要

**Comment by ShuzoN** [comment]
締切 8/10

**Comment by takegue** [comment]
これって done ?

**Comment by ShuzoN** [comment]
ダンじゃないはず. destroyのissueが解決次第って感じやな. 
とりあえず2016年の団体を遮蔽するスクリプトは #155で作ってある
