### ISSUE TITLE
参加団体のメーリングリスト作成, またはCSV出力機能追加

### ISSUE THREAD

**Issue by ShuzoN** [NUTFes/group-manager#176]
### 背景
参加団体に全体連絡を行うメーリングリストを現状では手動で追加, 管理している.
   
### 解決方法
参団アプリで管理 or 参団アプリ内のデータをCSVで出力する機能を追加する.  

----
deviseで出来る機能だと思う. 

追記2017/4/6
Googleフォームで読み込めるような形式でcsv出力

**Comment by kichikawa** [comment]
以下のようにインポートできるように
http://www.appsupport.jp/gmail/contact-csv/

必要な情報
必須
サークル名
メール

あれば嬉しい
代表者名
