### ISSUE TITLE
管理画面の検索や絞り込みが使いづらい

### ISSUE THREAD

**Issue by ShuzoN** [NUTFes/group-manager#181]
管理画面において, 右サイドバーに検索や絞り込み機能が存在する.  
これは管理画面生成gemの「active admin」が自動生成してくれている.  

が, 総務曰く非常に使いづらいらしい.  
ここを使いやすくする.
総務の要望を聞いて仕様を決めてください.  

---
11/15
 * 管理画面「物品貸出の申請」の 検索バーのGROUPの年度絞込み機能
管理画面「物品貸出の申請」のサイドバー"GROUP"でDBに登録されている全団体が表示される(過去も含めて). これを年度ごとに絞込できるようにしてほしい. 

 * 管理画面「物品貸出の申請」の一覧に参加団体形式を表示して欲しい. 
物品一覧を作成するときに団体名を都度クリックして参加団体形式を確認していた. 手間がかかるので, 一覧に団体形式を表示してほしい.

**Comment by kichikawa** [comment]
誰が言ったのかわからない
どうしてほしいのか明確に

**Comment by kichikawa** [comment]
管理画面「物品貸出の申請」の 検索バーのGROUPの年度絞込み機能
すぐほしい

管理画面「物品貸出の申請」の一覧に参加団体形式を表示して欲しい.
できればする
