### ISSUE TITLE
管理画面「貸出可能物品」に年度項目を表示する

### ISSUE THREAD

**Issue by ShuzoN** [NUTFes/group-manager#185]
管理画面「貸出可能物品」に年度項目が存在しない. 
2017年度の使用において使いづらくなると予想されるので年度項目を一覧に追加する

----
shuzonコメント
「StockerItem」テーブルがfes_year_idを持っているので, これを参照する.

**Comment by yyamnk** [comment]
ちょっと好みもあるけど，年度項目よりはenable/disableカラムを追加すればいいかな．
年度項目だと年度ごとにseedを生成しないといけないので．

**Comment by kkoike03** [comment]
過去の年の貸出可能物品の情報が必要になるか総務に確認
