### ISSUE TITLE
団体名をクリックすれば、今年申請した情報の全てが表示されるページを作って欲しい

### ISSUE THREAD

**Issue by ShuzoN** [NUTFes/group-manager#187]
以下は吹奏楽部の例であるが、一日目の何時からどこで演奏したいかなどの情報がこのページではわからない。一括で情報がわかるようにしてほしい（電力会場　高杉）

関連 : #18 

質問 : 最低限, 表示してほしい項目を洗い出して, どのようなページであれば使うかを提示して欲しい.(12/1 まで)

**Comment by kichikawa** [comment]
現状に代表者名と電話番号を追加してほしい(高杉)

**Comment by kichikawa** [comment]
項目名が日本語だと嬉しい

**Comment by ShuzoN** [comment]
新入生タスクに良さげ
