### ISSUE TITLE
[機能整理・追加]ステージ利用団体の共通項目を分離

### ISSUE THREAD

**Issue by kkoike03** [NUTFes/group-manager#19]
- 現状
    + 1日目，2日目，雨，晴れの4パターンそれぞれで「撮影許可」「大きな音」「自前の音響機材の使用」「BGM」を入力させている
    + 日付や天気に関わらず，これらを共通化したい

- 整理項目
    + 1日目，2日目，雨，晴れに限らず，1回のみ入力させるようにする
    + 入力フォームを既存のフォームから分離．新たにフォームを作る

- 追加項目
    + 新たな入力項目として，「出演内容」を追加（共通項目）

**Comment by TKNGUE** [comment]
データベースの移行がまだ
