### ISSUE TITLE
[機能追加] 全貸出物品の在庫情報 入力機能

### ISSUE THREAD

**Issue by yyamnk** [NUTFes/group-manager#20]
# 現状

貸出物品の在庫情報を管理していない．
在庫情報を入力し，システムで管理する

# 実装方法

## DB構造

* [新規作成] 物品場所のテーブル (StockerPlace) 
    - id
    - name: int (場所の名称)
    - is_available_fesdate: boolean (準備日の貸出場所かどうか)
* [新規作成] 在庫テーブル (StockedItem)
    - id
    - rental_item_id: reference
    - num: int (在庫数)
    - stocker_place_id: reference
* [新規作成] 貸出可能物品テーブル (RentableItem)
    - id
    - stocked_item_id: reference
    - stocker_place_id: reference (当日の貸出場所)
    - num: int (貸出可能な数量)

StockerPlaceはrails g model,
他は rails g scaffold
で作成する

## フォーム

* 在庫テーブルの入力・編集フォーム
    - 各物品の保管場所・数量を入力 (保管場所は準備日等で移動する前の場所)
* 貸出可能物品入力・編集フォーム
    - 在庫テーブルの各レコード (物品) の当日用貸出場所・数量を入力

**Comment by ShuzoN** [comment]
https://trello.com/c/JYGmegZZ/40--
