### ISSUE TITLE
HerokuのDBがいっぱい

### ISSUE THREAD

**Issue by yyamnk** [NUTFes/group-manager#209]
Heroku よりメールで警告がきた．

The database HEROKU_POSTGRESQL_JADE_URL on Heroku app nutfes-group-manager is approaching its allocated storage capacity.The database contains 7,970 rows. The Hobby-dev plan allows a maximum of 10,000 rows. If the databases exceeds 10,000 rows then INSERT privileges will be revoked, preventing more data from being written. INSERT privileges are automatically reinstated if rows are removed and the database once again complies with the plan limit.To avoid a disruption to your service, migrate the database to a Basic ($9/month) or higher plan:https://devcenter.heroku.com/articles/upgrade-heroku-postgres-with-pgbackupsIf you are unable to upgrade the database, you should limit or reduce the number of records in it.

**Comment by kichikawa** [comment]
管理者画面「貸出物品の割当」のデータが多いので毎年バックアップと削除を行う

**Comment by youichiro** [comment]
2年前までのデータだけ保持する
DB形式のバックアップだとすぐに参照できないので、JSON形式でバックアップしてほしい

**Comment by youichiro** [comment]
HerokuからVPSへの移行を行なったためcloseする
