### ISSUE TITLE
管理者ページで物品貸出の申請で数量０を表示しないで見やすくして欲しい

### ISSUE THREAD

**Issue by oba18** [NUTFes/group-manager#221]
物品貸出ページの申請の部分で０が表示されていると見にくいとのこと．

０の部分は非表示にする．

**Comment by youichiro** [comment]
![2018-02-21 16 14 16](https://user-images.githubusercontent.com/20487308/36467479-4b576264-1722-11e8-85c6-dfc09c1ac280.png)

- 参加団体アプリ > 管理者用 > 物品貸出の申請
- 申請されていない物品は表示しないようにする

**Comment by kichikawa** [comment]
0も見えないと確認する時に困ることになる気がするので，検索機能で「0より大きい」がデフォルトで表示されるようにする

**Comment by youichiro** [comment]
検索機能で頑張る
1ページの表示数増やす
ページネーションの設定: `config/initializers/kaminari_config.rb`
