### ISSUE TITLE
実施場所の申請ページでエリアマップを表示させる

### ISSUE THREAD

**Issue by kkoike03** [NUTFes/group-manager#235]
実施場所の申請ページにエリアマップが表示されていると希望場所を選びやすい

- 作業内容
    * GoogleDriveにエリアマップの画像を上げる
    * viewにリンクを貼って表示させる

**Comment by youichiro** [comment]
ロリポップにエリアマップをアップロードしたのでそのURLを使用する
http://nutfes.boo.jp/images/2018_area.jpg

**Comment by youichiro** [comment]
![2018-05-14 20 33 48](https://user-images.githubusercontent.com/20487308/39995106-51c4d71a-57b6-11e8-96f1-98134066a156.png)

エリアの情報が間違っているので修正する
エリアマップの情報(+規定外の場所)に合わせる
- 福利棟エリア→電気棟エリア
- 体育館エリア→削除（メインステージエリアと結合）
- 機械棟エリア→機械・建設エリア
- 生物エリア→削除

**Comment by youichiro** [comment]
研究室公開は「規定外の場所」を選択して欲しいので、説明を加える
