### ISSUE TITLE
ステージ企画団体は公演時間と準備・片付け時間を入力してもらう

### ISSUE THREAD

**Issue by youichiro** [NUTFes/group-manager#249]

**Comment by oba18** [comment]
## 概要
### 現状
ステージ利用の申請の際に開始時刻，終了時刻，使用時間幅を募集している．
<img width="1440" alt="2018-05-04 10 37 37" src="https://user-images.githubusercontent.com/33748835/39609911-89bf0f5a-4f87-11e8-815a-3b4084b2089b.png">

### 変更後の仕様
タブかチェックボックスで時間指定ありか，時間指定なしかを選択させる．
選択したものに該当する利用時間入力するフォームを出現させる．

＜時間指定なし＞
準備時間◯分　（5分区切りで0分から20分）
公演時間◯分　（30分区切りで30分から2時間）　
片付け時間◯分　　（5分区切りで0分から20分）
をプルダウンで登録させる．

＜時間指定あり＞
準備開始時刻◯時◯分
公演開始時刻◯時◯分
公演終了時刻◯時◯分
片付け終了時刻◯時◯分
（それぞれ◯分は15分刻み）
をプルダウンで登録させる．
