### ISSUE TITLE
[機能追加]電気・物品一覧の確認書類出力機能

### ISSUE THREAD

**Issue by TKNGUE** [NUTFes/group-manager#26]
![希望の画面](https://raw.githubusercontent.com/NUTFes/nutfes_docs/master/figs/%E9%9B%BB%E6%B0%97%E7%89%A9%E5%93%81%E4%B8%80%E8%A6%A7%E3%81%AE%E7%A2%BA%E8%AA%8D%E6%9B%B8%E9%A1%9E%E5%87%BA%E5%8A%9B%E6%A9%9F%E8%83%BD.jpg)

仕様の詳細 [電力・物品一覧 確認書類出力](https://github.com/NUTFes/nutfes_docs/blob/master/2015.10.26_group_manager.md)

要件確認
- 要件1
- 要件2
- 要件3

**Comment by ShuzoN** [comment]
コンフリクトを解消してください.

**Comment by youichiro** [comment]
https://github.com/NUTFes/group-manager/pull/366 で解決したのでcloseする
