### ISSUE TITLE
仕入先が重複している

### ISSUE THREAD

**Issue by oba18** [NUTFes/group-manager#268]
仕入先が重複している．

該当仕入先
・紅屋重正
・ひらせい長岡ニュータウン店

総務がアプリ上の管理者権限で削除することができなかった．

**Comment by oba18** [comment]
仕入先を追加するときに名前が一緒の場合はエラーにする．

**Comment by kichikawa** [comment]
あれ？
名前一致した時エラーになるのってなってた気がしたけど気のせい？

**Comment by youichiro** [comment]
エラー出ますね
なんで重複しているのか🤔

**Comment by kkoike03** [comment]
validationはきちんと設定されていますね．重複してるのは謎ですね．

ちなみに消せないのは外部キー制約なので，modelにassociationをちゃんと書いて，dependent: :destroyを設定すると消せます
