### ISSUE TITLE
検便リストを従業員の役割関係なく出力する

### ISSUE THREAD

**Issue by oba18** [NUTFes/group-manager#284]
2018年から検便は調理担当だけでなく，テントに入る全ての人にすることを義務付ける．
そのため，アプリでの検便リストを調理担当者の名前だけではなく，全従業員リストの名簿を出力できるようにする．

次年度には
検便の従業員登録では，役割分けは必要なくなるため，外部からの入力は必要なくなる．

**Comment by youichiro** [comment]
![2018-06-12 14 07 26](https://user-images.githubusercontent.com/20487308/41271161-f898743a-6e49-11e8-8c72-16d5311d2b60.png)

Employeeモデルのemployee_categoryカラムを表示しない
使わないかもしれないがカラムは残しておいても損はなさそう

**Comment by youichiro** [comment]
もともと担当業務によって出し分けるようにはなっていなかった
のでclose
