### ISSUE TITLE
PDF生成がローカルだとエラーになる問題

### ISSUE THREAD

**Issue by youichiro** [NUTFes/group-manager#294]
エラー
![2018-07-02 19 49 31](https://user-images.githubusercontent.com/20487308/42160045-c9fba920-7e30-11e8-89b1-8ac570c1e0db.png)

**Comment by youichiro** [comment]
gem `wkhtmltopdf-binary`を追加するとエラー出なくなる

**Comment by oba18** [comment]
はやくしろ

**Comment by oba18** [comment]
早くしろ

**Comment by oba18** [comment]
ごめんなさい

**Comment by youichiro** [comment]
解消されてたのでclose
