### ISSUE TITLE
未回答の場合エラーを出す

### ISSUE THREAD

**Issue by oba18** [NUTFes/group-manager#299]
未回答の場合は必ず入力しなければならないようにエラーを出力する
または”希望なし”という項目を作る

◯該当項目
 参加形式が食品販売か物品販売のとき
・実施場所
参加形式がステージ利用か展示・体験のとき
・ステージ利用

**Comment by oba18** [comment]
参加形式がステージ利用のときは
・ステージ利用の詳細
も

**Comment by youichiro** [comment]
![2018-07-23 18 22 34](https://user-images.githubusercontent.com/20487308/43068420-521c19dc-8ea5-11e8-9b23-afb529ad3343.png)
こんな感じで実施場所/ステージ利用/ステージ利用の詳細が入力されていなかったらワーニング(or エラー)を表示するようにする

**Comment by youichiro** [comment]
入力されていない項目を目立たせる

**Comment by oba18** [comment]
「希望なし」の項目が欲しいみたいです

**Comment by youichiro** [comment]
ステージ利用の申請では選択候補に"なし"が既にあると思うんだけど、"希望なし"を追加する必要あるかな🤔

**Comment by youichiro** [comment]
あ、ステージ利用の申請に関しては"未回答の場合は必ず入力しなければならないようにエラーを出力する"のほうをすればいいのか

**Comment by oba18** [comment]
そうですね，去年困ったのが未回答が多すぎてこれは本当にどこに入れてもいいのかどうかが判断できなかったので，参加形式が食品販売か物品販売のときは実施場所，ステージ利用の時はステージ利用の申請では未回答はエラーにして，”希望なし”という項目を作る感じです．

**Comment by youichiro** [comment]
実装する内容まとめ

[実施場所の申請] (食販, 物販)
- "希望なし"を選択肢に追加する
- "未回答"の状態(初期状態)のとき、DashbordにWarningを表示する

[ステージ利用の申請] (ステージ, 展示・体験)
- "なし"を"希望なし"に名前だけ変更する
- どれかが"未回答"の状態(初期状態)のとき、DashbordにWarningを表示する

[ステージ利用の詳細] (ステージ)
- "未回答"の状態(初期状態)のとき、DashbordにWarningを表示する
