### ISSUE TITLE
Development環境用のダミーのユーザ

### ISSUE THREAD

**Issue by TKNGUE** [NUTFes/group-manager#30]
ユーザアカウント登録がローカル環境だとうまくできなかったです.
原因は 登録確認用のメールが送れないことなのですが,

登録作業にメールを送るのも面倒ですので,
動作確認用にdevelopment環境だと ダミーユーザを生成するのはいかがでしょうか？

manager(2人)とdeveloper(1人)とuser(3~4人)ぐらいあれば良いかと

**Comment by ShuzoN** [comment]
PR #108 にて修正済み
