### ISSUE TITLE
ステージ利用の際に音被りをしてもいいかを入力してもらう機能

### ISSUE THREAD

**Issue by oba18** [NUTFes/group-manager#300]
執行部がタイムスケジュールを組むときに，音被りが問題になる．
現状では，ある程度スケジュールを組んでから，音被りの問題を探り，場合によっては総務局の参加団体部門がそれぞれの参加団体に音が被ってもよいかを確認する．
そのため，音が被っても大丈夫な団体かは先に把握しておきたい．

◯方法
参加形式がステージ利用のとき
ステージ利用の詳細のページに”音被りをしてもよいか”というカラムを追加する

**Comment by kichikawa** [comment]
これって「yes」or「no」の二択でいいのかな？
太鼓は嫌だけど他ならいいみたいなことない？

**Comment by oba18** [comment]
たしかにそういうことありそうですね，そしたら一概にyes/noでつくるの難しそうですね
