### ISSUE TITLE
[機能追加]全貸出物品入力機能

### ISSUE THREAD

**Issue by TKNGUE** [NUTFes/group-manager#33]
総務側が入力するための機能

**Comment by TKNGUE** [comment]
既に実装済みとのこと

**Comment by TKNGUE** [comment]
Herokuへpushしてないのでpushお願いします

**Comment by yyamnk** [comment]
https://github.com/NUTFes/group-manager/pull/24
でmasterへmargeしましたが，
権限が未設定なのと，topからのリンクが無いので実装します
