### ISSUE TITLE
StageOrder管理画面用フォームの編集

### ISSUE THREAD

**Issue by yyamnk** [NUTFes/group-manager#53]
`/admin/stage_orders/new`で追加ができない．

**Comment by yyamnk** [comment]
@kkoike03 
総務の担当者がActiveAdminからレコードの編集ができるようにフォームを作ってもらっていいですか?

希望場所の選択肢を`/stage_orders/ID/edit`と同様にセレクトボックスにしてほしいです．
時間幅と時刻はテキスト入力のままでいいでしょう．

**Comment by ShuzoN** [comment]
管理画面側からレコードを編集すると, エラーを吐きます. 
どうやら ``.empty?`` では レシーバが``nil``だった時にエラーを吐くようです. 
おそらくレコード生成時にtime_point_start / time_point_endが``nil``になっているのかな？
方法A : ``empty?`` -> ``nil?``に変更する
方法B : ``empty?``のまま, db側でdefault="", スクリプトで過去レコードのnilを変換するなどして対応してください. 

![update_stage_order_error](https://cloud.githubusercontent.com/assets/5877377/15298776/1699d586-1bdc-11e6-9448-e2e84bb0b0fb.jpg)

**Comment by yyamnk** [comment]
http://qiita.com/somewhatgood@github/items/b74107480ee3821784e6
あたりで対応できないでしょうか?

**Comment by ShuzoN** [comment]
@yyamnk blankで対応できそうですね. 
@kkoike03 よろしくお願いします!
