### ISSUE TITLE
貸出物品の申請に「椅子」が作成されないbug

### ISSUE THREAD

**Issue by ShuzoN** [NUTFes/group-manager#68]
「木の椅子」, 「パイプ椅子」ともに貸出物品として表示されない.

**Comment by yyamnk** [comment]
https://github.com/NUTFes/group-manager/pull/37
で変更したので，シードを変更するか管理画面から修正してください

**Comment by ShuzoN** [comment]
椅子に関して

できれば, どちらかの種類の椅子に統一したい. 
「椅子」というカテゴリで数を申請してもらい, それを総務側で自由に割り振りたい.

**Comment by ShuzoN** [comment]
@yyamnk 了解です.

**Comment by ShuzoN** [comment]
@yyamnk シード変更で対応します.

**Comment by yyamnk** [comment]
椅子は使わないことにしました．
