### ISSUE TITLE
「生鮮食品 購入リスト」について, ヒントを変更する

### ISSUE THREAD

**Issue by ShuzoN** [NUTFes/group-manager#75]
購入リスト登録 の 「生鮮食品」, 「提供品」の申請フォームのヒントを変更する. 

問題点: 
 1レコードに対して, 複数の仕入品を記入するユーザが居る
 自由記述欄の下にあるヒントを変更することで対応する

```
従来のヒント : 
1つの仕入先から購入する「生鮮食品」を列挙して下さい．例)じゃがいも，鶏肉
新規のヒント :
1つの仕入先から購入する「生鮮食品」を１つ入力して下さい．例)じゃがいも
```

**Comment by yyamnk** [comment]
@ShuzoN 従来はこの仕様でしたが，変更するんでしょうか?

**Comment by ShuzoN** [comment]
@yyamnk 前回のMTGでそう改良して欲しいとのこと(@tororo)でした.

**Comment by ShuzoN** [comment]
@yyamnk 
入力形式はどちらでもよいのですが, 
後に資料化しやすいのは1レコード1品目の入力方法ですね. 
過去のテンプレートを参考にあげておきます. 
![default](https://cloud.githubusercontent.com/assets/5877377/15446766/810dd9d0-1f65-11e6-9b9d-7ef414a50c3d.jpg)

**Comment by yyamnk** [comment]
上げてもらったのは去年に手入力で作成されたやつです。
一昨年以前は保健所のテンプレートに合わせて、１仕入れ先に複数の品目を記入してました。

現状で１仕入れ先に対して１テキスト (複数品目を入れる) でいいんじゃないでしょうか？
１品目ごとに１レコードにする理由がないので。

**Comment by ShuzoN** [comment]
今年度も現状維持で運用する
