### ISSUE TITLE
Stageモデルの管理画面がない

### ISSUE THREAD

**Issue by yyamnk** [NUTFes/group-manager#81]
`app/admin/stage.rb`を生成する

### 表示項目
id, name_ja, name_en, enable_sunny, enable_rainy

### モデルに対する権限設定
ManagerはCRUDのうち, RUだけ行えるように設定してください. 
cancancanで設定します.  
``app/models/ability.rb``のrole_id==2 に対して cannot [create, delete]すればokです. 

依存: issue #58

**Comment by ShuzoN** [comment]
active admin周りの操作や情報は, issue #55に書いてあるので適宜読んでください.
