### ISSUE TITLE
貸出物品に電ドラを追加するかどうかを総務に確認

### ISSUE THREAD

**Issue by ShuzoN** [NUTFes/group-manager#91]
電ドラの扱いをどうするか総務に確認する
物品持出し（各団体向け）表 [[団体別物品貸出票]](https://trello-attachments.s3.amazonaws.com/56210a2767e7603131504585/5627950827e4be253659b23b/2386189700bba580c9258c8525fc1d6d/%E5%9B%A3%E4%BD%93%E5%88%A5%E7%89%A9%E5%93%81%E8%B2%B8%E5%87%BA%E7%A5%A8_%E6%83%85%E5%A0%B1_%E7%A2%BA%E8%AA%8D.docx)に電ドラの数量を書く欄がある. 

電ドラを例年どのように扱っているか総務に問い合わせする.

**Comment by yyamnk** [comment]
@ShuzoN 去年のそれはミスだったはず．
電ドラは食品販売団体と電力配分を考えて総務が敷設するので，ユーザは触りません．
なのでその欄は無くていいはずです．

**Comment by ShuzoN** [comment]
@yyamnk 了解しました. closeします.
